repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        name: gitleaks detect secrets
        entry: gitleaks detect --no-git -v --redact
        language: golang
        types: [file]
        pass_filenames: false
