apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: litellm-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm
        command: ["litellm"]
        args: ["--port", "4000", "--config", "/app/config.yaml", "--detailed_debug"]
        ports:
        - containerPort: 4000
        env:
          - name: OLLAMA_API_BASE
            value: http://ollama-model-phi.ollama-apps.svc.cluster.local:11434
        resources:
          requests:
            cpu: "750m"
            memory: "2GiMi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeMounts:
        - name: litellm-config
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: prisma-cache
          mountPath: /root/.cache/prisma-python
          subPath: prisma-cache
      volumes:
      - name: litellm-config
        configMap:
          name: litellm-config
      - name: prisma-cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: litellm-gateway
spec:
  selector:
    app: litellm
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP 